const BOOKS_DB = [
    
    { name: "ברכות", category: "תלמוד בבלי", units: 126 }, 
    { name: "שבת", category: "תלמוד בבלי", units: 314 }, 
    { name: "עירובין", category: "תלמוד בבלי", units: 210 }, 
    { name: "פסחים", category: "תלמוד בבלי", units: 242 }, 
    { name: "שקלים", category: "תלמוד בבלי", units: 44 }, 
    { name: "יומא", category: "תלמוד בבלי", units: 176 }, 
    { name: "סוכה", category: "תלמוד בבלי", units: 112 }, 
    { name: "ביצה", category: "תלמוד בבלי", units: 80 }, 
    { name: "ראש השנה", category: "תלמוד בבלי", units: 70 }, 
    { name: "תענית", category: "תלמוד בבלי", units: 62 }, 
    { name: "מגילה", category: "תלמוד בבלי", units: 64 }, 
    { name: "מועד קטן", category: "תלמוד בבלי", units: 58 }, 
    { name: "חגיגה", category: "תלמוד בבלי", units: 54 }, 
    { name: "יבמות", category: "תלמוד בבלי", units: 244 }, 
    { name: "כתובות", category: "תלמוד בבלי", units: 224 }, 
    { name: "נדרים", category: "תלמוד בבלי", units: 182 }, 
    { name: "נזיר", category: "תלמוד בבלי", units: 132 }, 
    { name: "סוטה", category: "תלמוד בבלי", units: 98 }, 
    { name: "גיטין", category: "תלמוד בבלי", units: 180 }, 
    { name: "קידושין", category: "תלמוד בבלי", units: 164 }, 
    { name: "בבא קמא", category: "תלמוד בבלי", units: 238 }, 
    { name: "בבא מציעא", category: "תלמוד בבלי", units: 238 }, 
    { name: "בבא בתרא", category: "תלמוד בבלי", units: 352 }, 
    { name: "סנהדרין", category: "תלמוד בבלי", units: 226 }, 
    { name: "מכות", category: "תלמוד בבלי", units: 48 }, 
    { name: "שבועות", category: "תלמוד בבלי", units: 98 }, 
    { name: "עבודה זרה", category: "תלמוד בבלי", units: 152 }, 
    { name: "הוריות", category: "תלמוד בבלי", units: 28 }, 
    { name: "זבחים", category: "תלמוד בבלי", units: 240 }, 
    { name: "מנחות", category: "תלמוד בבלי", units: 236 }, 
    { name: "חולין", category: "תלמוד בבלי", units: 284 }, 
    { name: "בכורות", category: "תלמוד בבלי", units: 122 }, 
    { name: "ערכין", category: "תלמוד בבלי", units: 68 }, 
    { name: "תמורה", category: "תלמוד בבלי", units: 68 }, 
    { name: "כריתות", category: "תלמוד בבלי", units: 56 }, 
    { name: "מעילה", category: "תלמוד בבלי", units: 44 }, 
    { name: "תמיד", category: "תלמוד בבלי", units: 16 },   
    { name: "מידות", category: "תלמוד בבלי", units: 74 }, 
    { name: "קינים", category: "תלמוד בבלי", units: 8 }, 
    { name: "נידה", category: "תלמוד בבלי", units: 146 }, 


    
    { name: "ירושלמי ברכות", category: "תלמוד ירושלמי", units: 136 }, 
    { name: "ירושלמי פאה", category: "תלמוד ירושלמי", units: 74 },   
    { name: "ירושלמי דמאי", category: "תלמוד ירושלמי", units: 68 },  
    { name: "ירושלמי כלאיים", category: "תלמוד ירושלמי", units: 88 }, 
    { name: "ירושלמי שביעית", category: "תלמוד ירושלמי", units: 62 }, 
    { name: "ירושלמי תרומות", category: "תלמוד ירושלמי", units: 116 }, 
    { name: "ירושלמי מעשרות", category: "תלמוד ירושלמי", units: 52 }, 
    { name: "ירושלמי מעשר שני", category: "תלמוד ירושלמי", units: 56 }, 
    { name: "ירושלמי חלה", category: "תלמוד ירושלמי", units: 56 },   
    { name: "ירושלמי ערלה", category: "תלמוד ירושלמי", units: 40 },   
    { name: "ירושלמי ביכורים", category: "תלמוד ירושלמי", units: 26 }, 
    { name: "ירושלמי שבת", category: "תלמוד ירושלמי", units: 184 },  
    { name: "ירושלמי עירובין", category: "תלמוד ירושלמי", units: 130 }, 
    { name: "ירושלמי פסחים", category: "תלמוד ירושלמי", units: 142 }, 
    { name: "ירושלמי יומא", category: "תלמוד ירושלמי", units: 84 },   
    { name: "ירושלמי שקלים", category: "תלמוד ירושלמי", units: 66 },  
    { name: "ירושלמי סוכה", category: "תלמוד ירושלמי", units: 52 },   
    { name: "ירושלמי ראש השנה", category: "תלמוד ירושלמי", units: 44 }, 
    { name: "ירושלמי ביצה", category: "תלמוד ירושלמי", units: 44 },   
    { name: "ירושלמי תענית", category: "תלמוד ירושלמי", units: 52 },  
    { name: "ירושלמי מגילה", category: "תלמוד ירושלמי", units: 68 },  
    { name: "ירושלמי חגיגה", category: "תלמוד ירושלמי", units: 44 },  
    { name: "ירושלמי מועד קטן", category: "תלמוד ירושלמי", units: 38 }, 
    { name: "ירושלמי יבמות", category: "תלמוד ירושלמי", units: 170 }, 
    { name: "ירושלמי כתובות", category: "תלמוד ירושלמי", units: 144 }, 
    { name: "ירושלמי נדרים", category: "תלמוד ירושלמי", units: 80 },   
    { name: "ירושלמי נזיר", category: "תלמוד ירושלמי", units: 112 },  
    { name: "ירושלמי סוטה", category: "תלמוד ירושלמי", units: 94 },   
    { name: "ירושלמי גיטין", category: "תלמוד ירושלמי", units: 108 }, 
    { name: "ירושלמי קידושין", category: "תלמוד ירושלמי", units: 96 },  
    { name: "ירושלמי בבא קמא", category: "תלמוד ירושלמי", units: 88 }, 
    { name: "ירושלמי בבא מציעא", category: "תלמוד ירושלמי", units: 58 }, 
    { name: "ירושלמי בבא בתרא", category: "תלמוד ירושלמי", units: 40 }, 
    { name: "ירושלמי סנהדרין", category: "תלמוד ירושלמי", units: 136 }, 
    { name: "ירושלמי שבועות", category: "תלמוד ירושלמי", units: 88 },  
    { name: "ירושלמי עבודה זרה", category: "תלמוד ירושלמי", units: 74 }, 
    { name: "ירושלמי הוריות", category: "תלמוד ירושלמי", units: 38 },  
    { name: "ירושלמי נידה", category: "תלמוד ירושלמי", units: 26 },    


    
    { name: "בראשית", category: "תנ\"ך", units: 50 },
    { name: "שמות", category: "תנ\"ך", units: 40 },
    { name: "ויקרא", category: "תנ\"ך", units: 27 },
    { name: "במדבר", category: "תנ\"ך", units: 36 },
    { name: "דברים", category: "תנ\"ך", units: 34 },

    
    { name: "יהושע", category: "תנ\"ך", units: 24 },
    { name: "שופטים", category: "תנ\"ך", units: 21 },
    { name: "שמואל א", category: "תנ\"ך", units: 31 },
    { name: "שמואל ב", category: "תנ\"ך", units: 24 },
    { name: "מלכים א", category: "תנ\"ך", units: 22 },
    { name: "מלכים ב", category: "תנ\"ך", units: 25 },

    
    { name: "ישעיהו", category: "תנ\"ך", units: 66 },
    { name: "ירמיהו", category: "תנ\"ך", units: 52 },
    { name: "יחזקאל", category: "תנ\"ך", units: 48 },

    
    { name: "הושע", category: "תנ\"ך", units: 14 },
    { name: "יואל", category: "תנ\"ך", units: 4 },
    { name: "עמוס", category: "תנ\"ך", units: 9 },
    { name: "עובדיה", category: "תנ\"ך", units: 1 },
    { name: "יונה", category: "תנ\"ך", units: 4 },
    { name: "מיכה", category: "תנ\"ך", units: 7 },
    { name: "נחום", category: "תנ\"ך", units: 3 },
    { name: "חבקוק", category: "תנ\"ך", units: 3 },
    { name: "צפניה", category: "תנ\"ך", units: 3 },
    { name: "חגי", category: "תנ\"ך", units: 2 },
    { name: "זכריה", category: "תנ\"ך", units: 14 },
    { name: "mלאכי", category: "תנ\"ך", units: 3 },

    
    { name: "תהילים", category: "תנ\"ך", units: 150 },
    { name: "משלי", category: "תנ\"ך", units: 31 },
    { name: "איוב", category: "תנ\"ך", units: 42 },
    { name: "שיר השירים", category: "תנ\"ך", units: 8 },
    { name: "רות", category: "תנ\"ך", units: 4 },
    { name: "איכה", category: "תנ\"ך", units: 5 },
    { name: "קהלת", category: "תנ\"ך", units: 12 },
    { name: "אסתר", category: "תנ\"ך", units: 10 },
    { name: "דניאל", category: "תנ\"ך", units: 12 },
    { name: "עזרא", category: "תנ\"ך", units: 10 },
    { name: "נחמיה", category: "תנ\"ך", units: 13 },
    { name: "דברי הימים א", category: "תנ\"ך", units: 29 },
    { name: "דברי הימים ב", category: "תנ\"ך", units: 36 },

    
    { name: "ברכות (משנה)", category: "משנה", units: 9 },
    { name: "פאה", category: "משנה", units: 8 },
    { name: "דמאי", category: "משנה", units: 7 },
    { name: "כלאיים", category: "משנה", units: 9 },
    { name: "שביעית", category: "משנה", units: 10 },
    { name: "תרומות", category: "משנה", units: 11 },
    { name: "מעשרות", category: "משנה", units: 5 },
    { name: "מעשר שני", category: "משנה", units: 5 },
    { name: "חלה", category: "משנה", units: 4 },
    { name: "ערלה", category: "משנה", units: 3 },
    { name: "ביכורים", category: "משנה", units: 3 },
    { name: "שבת (משנה)", category: "משנה", units: 24 },
    { name: "עירובין (משנה)", category: "משנה", units: 10 },
    { name: "פסחים (משנה)", category: "משנה", units: 10 },
    { name: "שקלים (משנה)", category: "משנה", units: 8 },
    { name: "יומא (משנה)", category: "משנה", units: 8 },
    { name: "סוכה (משנה)", category: "משנה", units: 5 },
    { name: "ביצה (משנה)", category: "משנה", units: 5 },
    { name: "ראש השנה (משנה)", category: "משנה", units: 4 },
    { name: "תענית (משנה)", category: "משנה", units: 4 },
    { name: "מגילה (משנה)", category: "משנה", units: 4 },
    { name: "מועד קטן (משנה)", category: "משנה", units: 3 },
    { name: "חגיגה (משנה)", category: "משנה", units: 3 },
    { name: "יבמות (משנה)", category: "משנה", units: 16 },
    { name: "כתובות (משנה)", category: "משנה", units: 13 },
    { name: "נדרים (משנה)", category: "משנה", units: 11 },
    { name: "נזיר (משנה)", category: "משנה", units: 9 },
    { name: "סוטה (משנה)", category: "משנה", units: 9 },
    { name: "גיטין (משנה)", category: "משנה", units: 9 },
    { name: "קידושין (משנה)", category: "משנה", units: 4 },
    { name: "בבא קמא (משנה)", category: "משנה", units: 10 },
    { name: "בבא מציעא (משנה)", category: "משנה", units: 10 },
    { name: "בבא בתרא (משנה)", category: "משנה", units: 10 },
    { name: "סנהדרין (משנה)", category: "משנה", units: 11 },
    { name: "מכות (משנה)", category: "משנה", units: 3 },
    { name: "שבועות (משנה)", category: "משנה", units: 8 },
    { name: "עדיות", category: "משנה", units: 8 },
    { name: "עבודה זרה (משנה)", category: "משנה", units: 5 },
    { name: "אבות", category: "משנה", units: 6 },
    { name: "הוריות (משנה)", category: "משנה", units: 3 },
    { name: "זבחים (משנה)", category: "משנה", units: 14 },
    { name: "מנחות (משנה)", category: "משנה", units: 13 },
    { name: "חולין (משנה)", category: "משנה", units: 12 },
    { name: "בכורות (משנה)", category: "משנה", units: 9 },
    { name: "ערכין (משנה)", category: "משנה", units: 9 },
    { name: "תמורה (משנה)", category: "משנה", units: 7 },
    { name: "כריתות (משנה)", category: "משנה", units: 6 },
    { name: "מעילה (משנה)", category: "משנה", units: 6 },
    { name: "תמיד (משנה)", category: "משנה", units: 7 },
    { name: "מידות (משנה)", category: "משנה", units: 5 },
    { name: "קינים (משנה)", category: "משנה", units: 3 },
    { name: "כלים", category: "משנה", units: 30 },
    { name: "אוהלות", category: "משנה", units: 18 },
    { name: "נגעים", category: "משנה", units: 14 },
    { name: "פרה", category: "משנה", units: 12 },
    { name: "טהרות", category: "משנה", units: 10 },
    { name: "מקואות", category: "משנה", units: 10 },
    { name: "נידה (משנה)", category: "משנה", units: 10 },
    { name: "מכשירין", category: "משנה", units: 6 },
    { name: "זבים", category: "משנה", units: 5 },
    { name: "טבול יום", category: "משנה", units: 4 },
    { name: "ידיים", category: "משנה", units: 4 },
    { name: "עוקצין", category: "משנה", units: 3 },



    
    { name: "שו\"ע - הלכות השכמת הבוקר", category: "הלכה", units: 7 },
    { name: "שו\"ע - הלכות נטילת ידיים", category: "הלכה", units: 11 },
    { name: "שו\"ע - הלכות תפילין", category: "הלכה", units: 20 },
    { name: "שו\"ע - הלכות ציצית", category: "הלכה", units: 17 },
    { name: "שו\"ע - הלכות ברכות השחר", category: "הלכה", units: 10 },
    { name: "שו\"ע - הלכות קריאת שמע", category: "הלכה", units: 25 },
    { name: "שו\"ע - הלכות תפילה", category: "הלכה", units: 45 },
    { name: "שו\"ע - הלכות נשיאת כפיים", category: "הלכה", units: 13 },
    { name: "שו\"ע - הלכות קריאת התורה", category: "הלכה", units: 14 },
    { name: "שו\"ע - הלכות ברכות הנהנין", category: "הלכה", units: 22 },
    { name: "שו\"ע - הלכות סעודה ונטילת ידיים", category: "הלכה", units: 31 },
    { name: "שו\"ע - הלכות תפילת המנחה והערב", category: "הלכה", units: 5 },
    { name: "שו\"ע - הלכות שבת", category: "הלכה", units: 184 },
    { name: "שו\"ע - הלכות עירובין", category: "הלכה", units: 51 },
    { name: "שו\"ע - הלכות ראש חודש", category: "הלכה", units: 11 },
    { name: "שו\"ע - הלכות פסח", category: "הלכה", units: 62 },
    { name: "שו\"ע - הלכות יום טוב", category: "הלכה", units: 33 },
    { name: "שו\"ע - הלכות חול המועד", category: "הלכה", units: 18 },
    { name: "שו\"ע - הלכות תעניות", category: "הלכה", units: 20 },
    { name: "שו\"ע - הלכות ראש השנה", category: "הלכה", units: 11 },
    { name: "שו\"ע - הלכות יום הכיפורים", category: "הלכה", units: 15 },
    { name: "שו\"ע - הלכות סוכה ולולב", category: "הלכה", units: 28 },
    { name: "שו\"ע - הלכות חנוכה", category: "הלכה", units: 13 },
    { name: "שו\"ע - הלכות מגילה ופורים", category: "הלכה", units: 12 },

    
    { name: "שו\"ע - הלכות שחיטה", category: "הלכה", units: 28 },
    { name: "שו\"ע - הלכות טרפות", category: "הלכה", units: 32 },
    { name: "שו\"ע - הלכות מליחה", category: "הלכה", units: 12 },
    { name: "שו\"ע - הלכות בשר בחלב", category: "הלכה", units: 11 },
    { name: "שו\"ע - הלכות תערובות", category: "הלכה", units: 13 },
    { name: "שו\"ע - הלכות עבודה זרה", category: "הלכה", units: 31 },
    { name: "שו\"ע - הלכות ריבית", category: "הלכה", units: 18 },
    { name: "שו\"ע - הלכות נדרים", category: "הלכה", units: 48 },
    { name: "שו\"ע - הלכות שבועות", category: "הלכה", units: 17 },
    { name: "שו\"ע - הלכות כיבוד אב ואם", category: "הלכה", units: 3 },
    { name: "שו\"ע - הלכות תלמוד תורה", category: "הלכה", units: 5 },
    { name: "שו\"ע - הלכות צדקה", category: "הלכה", units: 12 },
    { name: "שו\"ע - הלכות מילה", category: "הלכה", units: 7 },
    { name: "שו\"ע - הלכות פדיון הבן", category: "הלכה", units: 1 },
    { name: "שו\"ע - הלכות כלאי בגדים (שעטנז)", category: "הלכה", units: 9 },
    { name: "שו\"ע - הלכות מזוזה", category: "הלכה", units: 7 },
    { name: "שו\"ע - הלכות ספר תורה", category: "הלכה", units: 10 },
    { name: "שו\"ע - הלכות אבלות", category: "הלכה", units: 63 },

    
    { name: "שו\"ע - הלכות דיינים", category: "הלכה", units: 27 },
    { name: "שו\"ע - הלכות עדות", category: "הלכה", units: 10 },
    { name: "שו\"ע - הלכות הלוואה", category: "הלכה", units: 35 },
    { name: "שו\"ע - הלכות גביית מלווה", category: "הלכה", units: 11 },
    { name: "שו\"ע - הלכות טוען ונטען", category: "הלכה", units: 23 },
    { name: "שו\"ע - הלכות שותפים", category: "הלכה", units: 11 },
    { name: "שו\"ע - הלכות שלוחים", category: "הלכה", units: 6 },
    { name: "שו\"ע - הלכות מקח וממכר", category: "הלכה", units: 44 },
    { name: "שו\"ע - הלכות אונאה", category: "הלכה", units: 12 },
    { name: "שו\"ע - הלכות מתנה", category: "הלכה", units: 11 },
    { name: "שו\"ע - הלכות גזילה", category: "הלכה", units: 17 },
    { name: "שו\"ע - הלכות אבידה ומציאה", category: "הלכה", units: 14 },
    { name: "שו\"ע - הלכות נזיקין", category: "הלכה", units: 32 },
    { name: "שו\"ע - הלכות שכירות", category: "הלכה", units: 26 },

    
    { name: "שו\"ע - הלכות פריה ורביה", category: "הלכה", units: 5 },
    { name: "שו\"ע - הלכות אישות", category: "הלכה", units: 25 },
    { name: "שו\"ע - הלכות קידושין", category: "הלכה", units: 40 },
    { name: "שו\"ע - הלכות כתובות", category: "הלכה", units: 52 },
    { name: "שו\"ע - הלכות גיטין", category: "הלכה", units: 35 },
    { name: "שו\"ע - הלכות יבום וחליצה", category: "הלכה", units: 22 },
  
    

    { name: "משנה ברורה - הלכות השכמת הבוקר", category: "הלכה", units: 7 }, 
    { name: "משנה ברורה - הלכות נטילת ידיים", category: "הלכה", units: 4 }, 
    { name: "משנה ברורה - הלכות אשר יצר וברכות השחר", category: "הלכה", units: 10 }, 
    { name: "משנה ברורה - הלכות ציצית", category: "הלכה", units: 17 }, 
    { name: "משנה ברורה - הלכות תפילין", category: "הלכה", units: 20 }, 
    { name: "משנה ברורה - הלכות קריאת שמע", category: "הלכה", units: 25 }, 
    { name: "משנה ברורה - הלכות תפילה (עמידה)", category: "הלכה", units: 31 }, 
    { name: "משנה ברורה - הלכות חזרת הש\"ץ ונשיאת כפיים", category: "הלכה", units: 11 }, 
    { name: "משנה ברורה - הלכות קריאת התורה", category: "הלכה", units: 15 }, 
    { name: "משנה ברורה - הלכות נטילת ידיים וסעודה", category: "הלכה", units: 13 }, 
    { name: "משנה ברורה - הלכות ברכת המזון", category: "הלכה", units: 21 }, 
    { name: "משנה ברורה - הלכות ברכות הנהנין", category: "הלכה", units: 29 }, 
    { name: "משנה ברורה - הלכות שבת: הכנה וקידוש", category: "הלכה", units: 30 }, 
    { name: "משנה ברורה - הלכות שבת: סעודות ותפילה", category: "הלכה", units: 27 }, 
    { name: "משנה ברורה - הלכות שבת: ל\"ט מלאכות", category: "הלכה", units: 41 }, 
    { name: "משנה ברורה - הלכות שבת: מוקצה", category: "הלכה", units: 4 }, 
    { name: "משנה ברורה - הלכות שבת: הוצאה וטלטול", category: "הלכה", units: 19 }, 
    { name: "משנה ברורה - הלכות פסח", category: "הלכה", units: 63 }, 
    { name: "משנה ברורה - הלכות יום טוב", category: "הלכה", units: 31 }, 
    { name: "משנה ברורה - הלכות חול המועד", category: "הלכה", units: 14 }, 
    { name: "משנה ברורה - הלכות תעניות", category: "הלכה", units: 20 }, 
    { name: "משנה ברורה - הלכות ראש השנה", category: "הלכה", units: 11 }, 
    { name: "משנה ברורה - הלכות יום כיפור", category: "הלכה", units: 15 }, 
    { name: "משנה ברורה - הלכות סוכה ולולב", category: "הלכה", units: 28 }, 
    { name: "משנה ברורה - הלכות חנוכה", category: "הלכה", units: 13 }, 
    { name: "משנה ברורה - הלכות מגילה ופורים", category: "הלכה", units: 12 }, 

    
    { name: "רמב\"ם - ספר המדע (יסודי התורה, דעות, תשובה)", category: "הלכה", units: 46 },
    { name: "רמב\"ם - ספר אהבה (קריאת שמע, תפילה, מילה)", category: "הלכה", units: 45 },
    { name: "רמב\"ם - ספר זמנים (שבת, יו\"ט, שופר)", category: "הלכה", units: 100 },
    { name: "רמב\"ם - ספר נשים (אישות, גירושין)", category: "הלכה", units: 60 },
    { name: "רמב\"ם - ספר קדושה (מאכלות אסורות, שחיטה)", category: "הלכה", units: 35 },
    { name: "רמב\"ם - ספר הפלאה (נדרים, נזירות, ערכין)", category: "הלכה", units: 40 },
    { name: "רמב\"ם - ספר זרעים (תרומות, מעשרות, שמיטה)", category: "הלכה", units: 120 },
    { name: "רמב\"ם - ספר עבודה (בית הבחירה, כלי המקדש)", category: "הלכה", units: 95 },
    { name: "רמב\"ם - ספר קרבנות", category: "הלכה", units: 65 },
    { name: "רמב\"ם - ספר טהרה", category: "הלכה", units: 170 },
    { name: "רמב\"ם - ספר נזיקין (גזילה, אבידה, חובל ומזיק)", category: "הלכה", units: 45 },
    { name: "רמב\"ם - ספר קנין (מכירה, זכייה ומתנה)", category: "הלכה", units: 60 },
    { name: "רמב\"ם - ספר משפטים (שכירות, מלווה ולווה)", category: "הלכה", units: 85 },
    { name: "רמב\"ם - ספר שופטים (סנהדרין, מלכים ומלחמות)", category: "הלכה", units: 50 },

    
    { name: "מסילת ישרים", category: "מוסר ומחשבה", units: 26 },
    { name: "חובת הלבבות", category: "מוסר ומחשבה", units: 10 },
    { name: "שערי תשובה", category: "מוסר ומחשבה", units: 4 },
    { name: "אורחות צדיקים", category: "מוסר ומחשבה", units: 28 },
    { name: "תומר דבורה", category: "מוסר ומחשבה", units: 10 },
    { name: "נפש החיים", category: "מוסר ומחשבה", units: 4 },
    { name: "מורה נבוכים", category: "מוסר ומחשבה", units: 178 },
    { name: "הכוזרי", category: "מוסר ומחשבה", units: 5 },
];
